export const LOGINREQ ='LOGINREQ';
export const LOGINSUCC='LOGINSUCC';
export const LOGINFAIL='LOGINFAIL';

// clear error
export const CLEARERRORANDSMS ='CLEARERRORANDSMS ';

export const SIGNUPREQ ='SIGNUPREQ';
export const SIGNUPSUCC='SIGNUPSUCC';
export const SIGNUPFAIL='SIGNUPFAIL';

export const LOADUSERREQ ='LOADUSERREQ ';
export const LOADUSERSUCC='LOADUSERSUCC';
export const LOADUSERFAIL='LOADUSERFAIL';
// get email verification 
export const EMAILVERIFICATIONREQ ='EMAILVERIFICATIONREQ';
export const EMAILVERIFICATIONSUCC='EMAILVERIFICATIONSUCC';
export const EMAILVERIFICATIONFAIL='EMAILVERIFICATIONFAIL';
// add income
export const ADDINCOMEREQ ='ADDINCOMEREQ ';
export const ADDINCOMESUCC='ADDINCOMESUCC';
export const ADDINCOMEFAIL='ADDINCOMEFAIL';
// ADD EXPENSES
export const ADDEXPENSESREQ ='ADDEXPENSESREQ ';
export const ADDEXPENSESSUCC='ADDEXPENSESSUCC';
export const ADDEXPENSESFAIL='ADDEXPENSESFAIL';
// edit EXPENSES
export const EDITEXPENSESREQ ='EDITEXPENSESREQ ';
export const EDITEXPENSESSUCC='EDITEXPENSESSUCC';
export const EDITEXPENSESFAIL='EDITEXPENSESFAIL';
// edit EXPENSES
export const EDITINCOMEREQ ='EDITEXPENSESREQ ';
export const EDITINCOMESUCC='EDITEXPENSESSUCC';
export const EDITINCOMEFAIL='EDITEXPENSESFAIL';
// get EXPENSES
export const GETALLEXPENSESREQ ='GETEXPENSESREQ ';
export const GETALLEXPENSESSUCC='GETEXPENSESSUCC';
export const GETALLEXPENSESFAIL='GETEXPENSESFAIL';
// get INCOME
export const GETALLINCOMESREQ ='GETALLINCOMESREQ ';
export const GETALLINCOMESSUCC='GETALLINCOMESSUCC';
export const GETALLINCOMESFAIL='GETALLINCOMESFAIL';
// logout
export const LOGOUTUSERREQ ='LOGOUTUSERREQ ';
export const LOGOUTUSERSUCC='LOGOUTUSERSUCC';
export const LOGOUTUSERFAIL='LOGOUTUSERFAIL';